workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    # Using default Linux instance (free tier compatible)
    # Remove instance_type to use free tier, or use 'linux' for basic instance
    environment:
      node: 20.18.0  # Updated to Node 20 for Firebase compatibility
      java: 17  # Required by Android Gradle plugin (minimum Java 17)
      groups:
        # Add these environment variables in Codemagic UI:
        # - keystore_credentials (CM_KEYSTORE_PATH, CM_KEYSTORE_PASSWORD, CM_KEY_ALIAS, CM_KEY_PASSWORD)
        - keystore_credentials
      vars:
        ANDROID_PACKAGE: "com.connect.app"
        NODE_ENV: "production"
        # Set PATH to include node_modules/.bin so npx can find React Native CLI
        # This is set as an environment variable so Gradle can access it
        REACT_NATIVE_ROOT: "."
        # These will be set via Codemagic UI environment variables:
        # CM_KEYSTORE_PATH: path to your keystore file
        # CM_KEYSTORE_PASSWORD: your keystore password
        # CM_KEY_ALIAS: your key alias
        # CM_KEY_PASSWORD: your key password
    scripts:
      - name: Install npm dependencies
        script: |
          echo "Installing npm dependencies..."
          npm install --legacy-peer-deps
          echo "Verifying React Native CLI installation..."
          if [ -d "node_modules/@react-native-community/cli" ]; then
            echo "✓ React Native CLI found"
          else
            echo "Installing React Native CLI..."
            npm install --save-dev @react-native-community/cli --legacy-peer-deps
          fi
          echo "Setting up environment for Gradle autolinking..."
          # Create a .env file or set environment that Gradle can access
          # Ensure PATH includes node_modules/.bin for npx to find React Native CLI
          echo "export PATH=\"$(pwd)/node_modules/.bin:\$PATH\"" >> ~/.bashrc
          export PATH="$(pwd)/node_modules/.bin:$PATH"
          echo "Testing npx react-native config..."
          cd android
          npx react-native config > /dev/null 2>&1 && echo "✓ npx works from android directory" || echo "✗ npx failed from android directory"
          cd ..
      - name: Skip CocoaPods (Android build only)
        script: |
          echo "Skipping CocoaPods installation - Android build only"
          echo "CocoaPods is only needed for iOS builds"
      - name: Generate React Native autolinking config
        script: |
          echo "Generating React Native autolinking configuration..."
          echo "Current directory: $(pwd)"
          # Generate autolinking configuration file before Gradle runs
          # This prevents Gradle from needing to run npx during settings.gradle evaluation
          npx react-native config > /tmp/react-native-config.json 2>&1 || {
            echo "Warning: react-native config failed, but continuing..."
            echo "This is expected if autolinking config already exists"
          }
          # Create autolinking directory if it doesn't exist
          mkdir -p android/build/generated/autolinking
          echo "Autolinking setup complete"
      - name: Set up keystore
        script: |
          echo "Setting up keystore for signing..."
          # Codemagic stores uploaded files in $CM_KEYSTORE_PATH environment variable
          # The path points to the uploaded file location
          if [ -n "$CM_KEYSTORE_PATH" ]; then
            if [ -f "$CM_KEYSTORE_PATH" ]; then
              echo "Keystore file found at: $CM_KEYSTORE_PATH"
              echo "Copying keystore to android/app directory..."
              cp "$CM_KEYSTORE_PATH" android/app/connect-app.keystore
              echo "Keystore copied successfully"
              # Update CM_KEYSTORE_PATH to point to the new location for build.gradle
              export CM_KEYSTORE_PATH="android/app/connect-app.keystore"
            else
              echo "Warning: Keystore file not found at $CM_KEYSTORE_PATH"
              echo "Checking if keystore exists in android/app directory..."
              if [ -f "android/app/connect-app.keystore" ]; then
                echo "Using existing keystore in android/app directory"
                export CM_KEYSTORE_PATH="android/app/connect-app.keystore"
              else
                echo "Warning: No keystore found. Build will use debug keystore."
              fi
            fi
          else
            echo "CM_KEYSTORE_PATH not set. Checking for keystore in android/app directory..."
            if [ -f "android/app/connect-app.keystore" ]; then
              echo "Using existing keystore in android/app directory"
              export CM_KEYSTORE_PATH="android/app/connect-app.keystore"
            else
              echo "Warning: No keystore found. Build will use debug keystore."
            fi
          fi
      - name: Build Android Production APK
        script: |
          echo "Building Android Production APK..."
          echo "Current directory: $(pwd)"
          echo "Verifying React Native config..."
          if [ -f "app.json" ]; then
            echo "✓ app.json found at root"
            echo "Android package: $(cat app.json | grep -A 2 '"android"' | grep '"package"' | cut -d'"' -f4)"
          else
            echo "✗ app.json not found at root"
            exit 1
          fi
          echo "Verifying React Native CLI is available..."
          npx react-native --version || echo "Warning: React Native CLI check failed"
          echo "Testing React Native config command from project root..."
          npx react-native config || echo "Config command failed, but continuing..."
          echo "Setting up Android build environment..."
          # Set PATH to include project root node_modules/.bin so npx can find React Native CLI
          # This must be done before cd into android directory
          export PATH="$(pwd)/node_modules/.bin:$PATH"
          echo "PATH updated: $PATH"
          echo "Setting up Android build..."
          cd android
          chmod +x gradlew
          echo "Cleaning previous builds..."
          ./gradlew clean || true
          echo "Starting release build..."
          # Pass keystore properties as project properties for release signing
          # Use --no-daemon and --no-build-cache for CI/CD stability
          if [ -n "$CM_KEYSTORE_PATH" ] && [ -n "$CM_KEYSTORE_PASSWORD" ] && [ -n "$CM_KEY_ALIAS" ] && [ -n "$CM_KEY_PASSWORD" ]; then
            echo "Building with keystore signing..."
            ./gradlew assembleRelease \
              --no-daemon \
              --no-build-cache \
              -PCM_KEYSTORE_PATH="$CM_KEYSTORE_PATH" \
              -PCM_KEYSTORE_PASSWORD="$CM_KEYSTORE_PASSWORD" \
              -PCM_KEY_ALIAS="$CM_KEY_ALIAS" \
              -PCM_KEY_PASSWORD="$CM_KEY_PASSWORD" || exit 1
          else
            echo "Building with debug keystore (no release keystore configured)..."
            ./gradlew assembleRelease --no-daemon --no-build-cache || exit 1
          fi
          echo "Build completed. Checking for APK files..."
          find app/build/outputs/apk -name "*.apk" -type f || echo "No APK files found in app/build/outputs/apk"
          cd ..
      - name: Verify APK build output
        script: |
          echo "Verifying APK build output..."
          echo "Searching for APK files..."
          find android/app/build/outputs -name "*.apk" -type f 2>/dev/null || echo "No APK files found"
          echo ""
          echo "Checking common APK locations:"
          ls -la android/app/build/outputs/apk/ 2>/dev/null || echo "apk directory not found"
          ls -la android/app/build/outputs/apk/release/ 2>/dev/null || echo "release directory not found"
          echo ""
          # Check for APK in the expected location
          if [ -f "android/app/build/outputs/apk/release/app-release.apk" ]; then
            echo "✓ Production APK file found at expected location"
            ls -lh android/app/build/outputs/apk/release/app-release.apk
            echo "APK file size:"
            du -h android/app/build/outputs/apk/release/app-release.apk
          else
            echo "✗ APK file not found at expected location: android/app/build/outputs/apk/release/app-release.apk"
            echo "Searching for any APK files..."
            APK_FILE=$(find android/app/build/outputs -name "*.apk" -type f | head -1)
            if [ -n "$APK_FILE" ]; then
              echo "Found APK at: $APK_FILE"
              ls -lh "$APK_FILE"
              echo "Copying to expected location..."
              mkdir -p android/app/build/outputs/apk/release
              cp "$APK_FILE" android/app/build/outputs/apk/release/app-release.apk
              echo "✓ APK file copied to expected location"
            else
              echo "✗ No APK files found anywhere in build outputs"
              echo "Build may have failed. Check build logs above."
              exit 1
            fi
          fi
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
        notify:
          success: true
          failure: true
      google_play:
        # Uncomment and configure when ready to publish to Google Play
        # credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        # track: internal # or alpha, beta, production
        # submit_as_draft: true
