workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store # or ad_hoc, development, enterprise
        bundle_identifier: com.connect.app
      groups:
        - app_store_credentials # Add your App Store Connect API key credentials here
      vars:
        XCODE_WORKSPACE: "app/ios/Connect.xcworkspace"
        XCODE_SCHEME: "Connect"
        APP_ID: 1234567890 # Replace with your App Store Connect App ID
        BUNDLE_ID: "com.connect.app"
      node: 18.20.0
      cocoapods: default
    integrations:
      app_store_connect: integration
    scripts:
      - name: Install dependencies
        script: |
          cd app
          npm install
      - name: Install CocoaPods dependencies
        script: |
          cd app/ios
          pod install
      - name: Set up code signing settings on Xcode project
        script: |
          cd app/ios
          xcode-project use-profiles
      - name: Build ipa for App Store
        script: |
          cd app/ios
          xcodebuild \
            -workspace Connect.xcworkspace \
            -scheme Connect \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath build/Connect.xcarchive \
            archive \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="match AppStore com.connect.app"
      - name: Export IPA
        script: |
          cd app/ios
          xcodebuild -exportArchive \
            -archivePath build/Connect.xcarchive \
            -exportPath build/ipa \
            -exportMethod app-store \
            -allowProvisioningUpdates
    artifacts:
      - app/ios/build/ipa/*.ipa
      - app/ios/build/Connect.xcarchive
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
        notify:
          success: true
          failure: false
      app_store_connect:
        # Authentication with App Store Connect API key (configured in Codemagic UI)
        auth: integration
        # Submit to TestFlight
        submit_to_testflight: true
        beta_groups:
          - group name of testers # Add your TestFlight beta group name
        # Or submit to App Store
        # submit_to_app_store: true

