workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: linux
    environment:
      node: 18.20.0
      java: temurin-11
      vars:
        ANDROID_PACKAGE: "com.connect.app"
        NODE_ENV: "production"
    scripts:
      - name: Install npm dependencies
        script: |
          cd app
          npm install
      - name: Clean Gradle
        script: |
          cd android
          ./gradlew clean
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - user@example.com # Replace with your email
        notify:
          success: true
          failure: false
