'use strict';

/**
 * Remote access for the Expo control daemon.
 *
 * On the live site (e.g. https://connect-bd.online/expo) the browser reaches the
 * daemon through a Cloudflare quick tunnel run by PM2 (home-cobalt). Anyone who
 * learns a tunnel URL can send requests to it, so every request arriving
 * through the tunnel must carry the access key; only plain requests from this
 * machine (or the local web dev-server proxy) skip it.
 *
 * Settings come from the environment or, when unset, from home-cobalt/live.env
 * (same file the Cobalt and face-login services use):
 *   EXPO_CONTROL_ACCESS_KEY        required for remote access (generated by
 *                                  home-cobalt/install-expo-control.ps1)
 *   EXPO_CONTROL_ALLOWED_ORIGINS   comma-separated live site origins
 *                                  (default https://connect-bd.online and www)
 */

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const sys = require('./system');

const DEFAULT_REMOTE_ORIGINS = ['https://connect-bd.online', 'https://www.connect-bd.online'];
const CACHE_MS = 5000;

function createRemoteAccess({ projectRoot }) {
  const liveEnvFile =
    process.env.EXPO_CONTROL_LIVE_ENV || path.resolve(projectRoot, '..', 'home-cobalt', 'live.env');
  let cache = { at: 0, values: {} };

  function readLiveEnv() {
    if (Date.now() - cache.at < CACHE_MS) return cache.values;
    const values = {};
    try {
      for (const line of fs.readFileSync(liveEnvFile, 'utf8').split(/\r?\n/)) {
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#')) continue;
        const eq = trimmed.indexOf('=');
        if (eq === -1) continue;
        values[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim().replace(/^(['"])(.*)\1$/, '$2');
      }
    } catch (_) {
      // no live.env: remote access stays disabled
    }
    cache = { at: Date.now(), values };
    return values;
  }

  const setting = (key) => String(process.env[key] || readLiveEnv()[key] || '').trim();

  function getAccessKey() {
    return setting('EXPO_CONTROL_ACCESS_KEY');
  }

  function remoteOrigins() {
    const configured = setting('EXPO_CONTROL_ALLOWED_ORIGINS')
      .split(',')
      .map((origin) => origin.trim().replace(/\/$/, ''))
      .filter(Boolean);
    return configured.length ? configured : DEFAULT_REMOTE_ORIGINS;
  }

  /**
   * A request is local only when it targets this machine by name and carries
   * no proxy/tunnel headers. Cloudflare always adds cf-connecting-ip and the
   * tunnel hostname, so tunnel traffic can never pass as local.
   */
  function isRemote(req) {
    const host = String(req.headers.host || '').replace(/:\d+$/, '').replace(/^\[|\]$/g, '');
    const localHost = host === '127.0.0.1' || host === 'localhost' || host === '::1';
    const proxied = Boolean(req.headers['cf-connecting-ip'] || req.headers['x-forwarded-for'] || req.headers['cf-ray']);
    return !localHost || proxied || !sys.isPrivateAddress(req.socket.remoteAddress || '');
  }

  function isAllowedOrigin(origin, remote) {
    if (!origin) return true;
    const clean = origin.replace(/\/$/, '');
    if (remoteOrigins().includes(clean)) return true;
    if (remote) return false;
    try {
      const url = new URL(clean);
      if (!/^https?:$/.test(url.protocol)) return false;
      const host = url.hostname.replace(/^\[|\]$/g, '');
      return host === 'localhost' || host.endsWith('.localhost') || sys.isPrivateAddress(host);
    } catch (_) {
      return false;
    }
  }

  function presentedKey(req) {
    const header = String(req.headers['x-expo-control-key'] || req.headers.authorization || '');
    return header.replace(/^Bearer\s+/i, '').trim();
  }

  /** Constant-time check of the access key sent with a remote request. */
  function isAuthorized(req) {
    const expected = getAccessKey();
    const given = presentedKey(req);
    if (!expected || !given) return false;
    const a = crypto.createHash('sha256').update(expected).digest();
    const b = crypto.createHash('sha256').update(given).digest();
    return crypto.timingSafeEqual(a, b);
  }

  return { isRemote, isAllowedOrigin, isAuthorized, getAccessKey, remoteOrigins, liveEnvFile };
}

module.exports = { createRemoteAccess };
